#!/bin/bash


CPU_THRESHOLD=80
MEM_THRESHOLD=80      
DISK_THRESHOLD=80     
PROC_THRESHOLD=300
LOG_FILE="$HOME/cpu_health_log.txt"


log_alert() {
    echo "$(date) - $1" | tee -a "$LOG_FILE"
}



CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}')


CPU_USAGE=${CPU_USAGE%.*}


if [ "$CPU_USAGE" -gt "$CPU_THRESHOLD" ]; then
    log_alert "ALERT: High CPU Usage - $CPU_USAGE%"
else
    log_alert "CPU Usage is normal: $CPU_USAGE%"
fi


MEM_USAGE=$(free | awk '/Mem/ {printf("%.0f", $3/$2 * 100)}')

if [ "$MEM_USAGE" -gt "$MEM_THRESHOLD" ]; then
    log_alert "Memory usage is high: ${MEM_USAGE}%"
else
    log_alert "Memory Usage is normal: ${MEM_USAGE}%"
fi

DISK_USAGE=$(df / | awk 'NR==2 {print $5}' | sed 's/%//')

if [ "$DISK_USAGE" -gt "$DISK_THRESHOLD" ]; then
    log_alert "ALERT: High Disk Usage - $DISK_USAGE%"
else
    log_alert "Disk Usage is normal: $DISK_USAGE%"
fi


PROC_COUNT=$(ps aux --no-heading | wc -l)

if [ "$PROC_COUNT" -gt "$PROC_THRESHOLD" ]; then
    log_alert "ALERT: Too Many Processes Running - $PROC_COUNT"
else
    log_alert "Running Processes Count is normal: $PROC_COUNT"
fi
