apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: wisecow-container
        image: hustlerhimanshu/wisecow:sha-fea4c679c833cbcfec1b84651e80b151d6c84cca
        ports:
        - containerPort: 4499
